# Generated by Django 5.2.7 on 2025-11-06 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_alter_reserva_data_alter_reserva_horario'),
        ('pedidos', '0002_categoria_itempedido_observacoes_mesa_capacidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='guests.mesa'),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='tempo_preparo',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.DeleteModel(
            name='Comanda',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
