# Generated by Django 5.2.7 on 2025-11-06 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AddField(
            model_name='pagamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 6, 11, 50)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fornecedor'),
        ),
    ]
