# Generated by Django 5.2.7 on 2025-10-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=30)),
                ('nascimento', models.DateField(max_length=30)),
                ('horario', models.TimeField(max_length=10)),
                ('solicitacao_especial', models.CharField(max_length=1000)),
            ],
        ),
    ]
