# Generated by Django 5.2.7 on 2025-10-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='convidados',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nascimento',
            field=models.DateField(),
        ),
    ]
