# Generated by Django 5.2.7 on 2025-10-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_pessoa_convidados_alter_pessoa_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('convidados', models.IntegerField()),
                ('horario', models.TimeField()),
                ('solicitacao_especial', models.TextField(blank=True)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('espera', 'Em Espera'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='espera', max_length=20)),
                ('posicao_fila', models.IntegerField(default=0)),
            ],
        ),
    ]
