# Generated by Django 5.2.7 on 2025-10-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
