# Generated by Django 5.2.7 on 2025-10-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_delete_pessoa_alter_reserva_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
