# Generated by Django 5.2.7 on 2025-10-25 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_reserva_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(),
        ),
    ]
