# Generated by Django 5.2.7 on 2025-10-25 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_reserva_data_alter_reserva_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
