# Generated by Django 5.2.7 on 2025-10-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_mesa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='data_reserva',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='reserva',
        ),
        migrations.AddField(
            model_name='mesa',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='guests.mesa'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidade',
            field=models.IntegerField(verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Número da Mesa'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('limpeza', 'Em Limpeza')], default='livre', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('espera', 'Em Espera'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='espera', max_length=20),
        ),
    ]
