# Generated by Django 5.2.7 on 2025-10-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0009_alter_mesa_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(verbose_name='Data da Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(verbose_name='Horário da Reserva'),
        ),
    ]
